### ISSUE TITLE
Not able to ignore the fields in jsons

### ISSUE THREAD

**Issue by nikhilbhavsar5895** [wI2L/jsondiff#10]
Hi,

Not able to ignore fields in JSON while comparing. Can any one give the example?

**Comment by wI2L** [comment]
Hello @nikhilbhavsar5895

Short answer, no it's not possible to instruct the lib to ignore one or more fields during the comparison.

I don't know if it make sense to add a feature like it, since the removal of fields that shouldn't be compared could be done prior to the comparison.

I'm going to check if it is easily doable in a practicable way.

**Comment by wI2L** [comment]
@nikhilbhavsar5895 @krunal-lia

I implemented a new option in this [commit](https://github.com/wI2L/jsondiff/commit/c0f2ef4ae2c730b0f51368842324a8205933ff78).

I'll make a new pre-release in the next days. Keep in mind that I may update the implementation of this option in the future.
