### ISSUE TITLE
Misleading diff when removing/adding an element in an array

### ISSUE THREAD

**Issue by dragan-sysdig** [wI2L/jsondiff#17]
Hi @wI2L,
First of all I wanted to thank you for publicly sharing this great lib. It seems to work perfectly, but it seems it has a flaw, that besides it doesn't generate a proper diff, but it also doesn't follow the [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902). If you take  for example an array of let's say 5 elements, and remove (the same behavior is with adding) the middle one (3rd one), generated diff will show like the last element was removed and all the elements before the last one and up to the actual removed element had a replace operation. Which is not true and might be confusing. Applying that patch will eventually result in the right json version (like if we just removed the questioned element), and in that perspective the patch is not completely wrong, but it would be much more practical and correct to show the exact change, which is operation remove at path array/3, which is what standard also describes [here](https://datatracker.ietf.org/doc/html/rfc6902#appendix-A.4), rather than generating bunch of non existing operations. Please take a look at this example: https://go.dev/play/p/HiI7tbaQ47C.

**Comment by wI2L** [comment]
Hello,
Yep, that's something I'm aware of.
It's related to the array diffing process [here](https://github.com/wI2L/jsondiff/blob/master/differ.go#L271), and can surely be improved to optimize the operations generated.

**Comment by dragan-sysdig** [comment]
Thank you for your quick response. Are there any plans for a fix for this any time soon?

**Comment by wI2L** [comment]
@dragan-sysdig
Please see this [commit](https://github.com/wI2L/jsondiff/commit/a434103361452f8942bc7d9bf0eac6f7fe2fd879) for an *experimental* implementation.

I have yet to add more tests to cover all potential cases (addition, deletion, change), but I have reproduced the expected behavior from your [example](https://go.dev/play/p/HiI7tbaQ47C).

Note that the new LCS-based array comparison function does not generate move or replace operations. It is inspired by the [`Algorithm::Diff#sdiff`](https://metacpan.org/pod/Algorithm::Diff#sdiff) subroutine.

**Comment by wI2L** [comment]
Added more tests in https://github.com/wI2L/jsondiff/commit/80dc0ed193b20a90cbaa3ef8f6009ee2947fd4fe, and fixed a bug related to indices shift.

**Comment by dragan-sysdig** [comment]
Great job @wI2L! I did some preliminary testing and it seems it's working! This really means a lot!

**Comment by wI2L** [comment]
Glad it helped, that's a good improvement over the current behavior TBH, so thanks for the report.
