### ISSUE TITLE
verifying module: checksum mismatch

### ISSUE THREAD

**Issue by grandeto** [wI2L/jsondiff#19]
```
github.com/wI2L/jsondiff: github.com/wI2L/jsondiff@v0.5.1: verifying module: checksum mismatch
	downloaded: h1:BCzyP6xQWeF7XSPMNeVJNzxUEJ4BBeMn2KQxNuozyWU=
	sum.golang.org: h1:xS4zYUspH4U3IB0Lwo9+jv+MSRJSWMF87Y4BpDbFMHo=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by wI2L** [comment]
@grandeto

```
github.com/wI2L/jsondiff v0.5.1 h1:xS4zYUspH4U3IB0Lwo9+jv+MSRJSWMF87Y4BpDbFMHo=
```
This is indeed what I get when I get this exact version.
Could you try to clean your modules caches and see if it happens again ?

**Comment by grandeto** [comment]
> github.com/wI2L/jsondiff v0.5.1

tested both `go clean -modcache` and `GOSUMDB="sum.golang.org" go get github.com/wI2L/jsondiff@v0.5.1` on a brand new machine, never downloaded the pkg before

no change.

on the contrary, no issue with v0.5.0

**Comment by wI2L** [comment]
Usually this kind of shenanigans happens when the tag is replaced/repushed, and the proxy had the time to cache the version, but I don't remember messing with this tag in particular, nor can I replicate the issue on machine with the official Go proxy.

Could you please confirm that the `GOPROXY` env var points to the office proxy.golang.org ?

I'll dig a bit more about this issue, but I bet that pushing a new tag and retracting this one will probably be the way to go.

**Comment by wI2L** [comment]
Could you retry with:
`GOPROXY=https://proxy.golang.org,direct` in env, and `go clean -modcache` followed by a `go mod tidy` ?

**Comment by grandeto** [comment]
`https://proxy.golang.org` did the trick

in my case `GOPROXY` was just `direct`

thanks. closing...
