### ISSUE TITLE
feature: expose `apply` function

### ISSUE THREAD

**Issue by gm0stache** [wI2L/jsondiff#25]
hi there!

would it be possible to expose the [apply](https://github.com/wI2L/jsondiff/blob/9bbbc455e35f046a33301fbe8f973f2b2a288e93/apply.go#L18C1-L18C24) function?

thanks for all your work! highly appreciate this package!

cheers!

**Comment by wI2L** [comment]
@gm0stache

This function was added only for test cases, because I wasn't satisfied with [evanphx/json-patch](https://github.com/evanphx/json-patch) and it was buggy for some valid JSON Patches.

However, this package only focuses on the creation of patches, not applying them. Also note that you probably wouldn't want to use the `apply` function that this package use, because it is not optimized.
