### ISSUE TITLE
[feature request]: Show old value for replace operations

### ISSUE THREAD

**Issue by tjdavis3** [wI2L/jsondiff#4]
Factorize() only shows from on move and copy operations.  In our use case we are not generating the diffs for use with a PATCH but to show changes.  We'd like to be able to generate the diff so that it shows both the old and new values of the changed fields.

We tried using Factorize() but that doesn't change the output for replace operations.  It appears the append method explicitly sets the from value to emptyPtr.  It looks like there may be a few other places that changes would be needed to set the old value.  

Ideally we'd like to see a replace able to be renders as

```json
{"op":"replace","from":"oldValue","path":"/key","value":"newValue"}
```

**Comment by wI2L** [comment]
The `from` location is specified in the [spec](https://datatracker.ietf.org/doc/html/rfc6902) for `move` and `copy` operations only. For the other type of operations, there is no notion of a "old location". A location is not a value, but the path that referenced the previous value, and it's applicable to only the two operations mentionned before.

I think you are perhaps confusing that field with the [`OldValue`](https://github.com/wI2L/jsondiff/blob/master/operation.go#L24) field, which sounds like it's what you're interested in. See the [`differ.replace`](https://github.com/wI2L/jsondiff/blob/master/differ.go#L224) method. It does pass the "old value" for a replace operation. However, since the rfc6902 doesn't mention it, the field is not marshaled by default if you use `encoding/json.Marshal`, but it's present and you can consume it to show the difference of values.
