### ISSUE TITLE
Support replace operations with value of null

### ISSUE THREAD

**Issue by kingtaj** [wI2L/jsondiff#7]
When setting a json field to null, the patch produces a replace operation like this:
```
{"op":"replace","path":"/test_int_ptr"}
```
with no `value` field.

Is there perhaps a configuration option to produce an operation with null/nil instead?
```
{"op":"replace","path":"/test_int_ptr",value:null}
```
Thank you.

**Comment by kingtaj** [comment]
Thanks for the quick turnaround!

**Comment by wI2L** [comment]
@kingtaj I just realised that there's one case where the current implementation will fail to met the expected output once an operation is marshaled to JSON; when the value (which has type `interface{}`) is not `nil` but a typed-nil value (`nil` vs `(*int)(nil)` for example).

**Comment by kingtaj** [comment]
thanks, good catch

**Comment by wI2L** [comment]
@kingtaj Updated the PR with a new commit, if you want to check it out!

I'm using `unsafe` to avoid `reflect`. One could check is `reflect.ValueOf(o.Value).IsNil()` is `true`, but that would require to ensure that the underlying type of `o.Value` is nill-able (map, slice, pointer or func/chan -- event tho the last two can be excluded since not supported by `encoding/json`).

**Comment by kingtaj** [comment]
👍 Nice! Yeah I didn't think you'd want to use `reflect` if it could be avoided.

**Comment by wI2L** [comment]
@kingtaj Release with v0.3.0. Thanks again for the issue reporting.
